#!/usr/bin/env python
import os
from subprocess import check_output

possible = ['.venv', '.env', 'venv', 'env']

for p in possible:
    if os.path.exists(p) and os.path.isdir(p):
        print(p)
        exit(0)

# very important to throw away the output!
check_output('virtualenv -p python3 %s' % possible[0], shell=True)
print(possible[0])
